{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "db-provision-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "db-provision-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "db-provision-operator.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "db-provision-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
