apiVersion: v1
entries:
  db-provision-operator:
  - apiVersion: v2
    appVersion: 0.1.3
    created: "2026-01-22T12:23:57.435800624Z"
    description: A Kubernetes operator for managing database provisioning (databases,
      users, roles, grants, backups)
    digest: 7030636ecaf553b07fe81b38c7a9958cc4897a4da57c96cf248d9d74eaf11784
    home: https://github.com/panteparak/db-provision-operator
    keywords:
    - database
    - postgresql
    - mysql
    - operator
    - kubernetes
    - provisioning
    - backup
    kubeVersion: '>=1.26.0-0'
    maintainers:
    - name: panteparak
    name: db-provision-operator
    sources:
    - https://github.com/panteparak/db-provision-operator
    type: application
    urls:
    - https://panteparak.github.io/db-provision-operator/charts/db-provision-operator-0.1.3.tgz
    version: 0.1.3
generated: "2026-01-22T12:23:57.43470574Z"
