apiVersion: v1
entries:
  db-provision-operator:
  - apiVersion: v2
    appVersion: 0.1.7
    created: "2026-01-28T08:06:20.133530202Z"
    description: A Kubernetes operator for managing database provisioning (databases,
      users, roles, grants, backups)
    digest: b723eab975f03041798dc56619943e0a4d5c7b446faaa5801d829ba9da6d4c8f
    home: https://github.com/panteparak/db-provision-operator
    keywords:
    - database
    - postgresql
    - mysql
    - operator
    - kubernetes
    - provisioning
    - backup
    kubeVersion: '>=1.26.0-0'
    maintainers:
    - name: panteparak
    name: db-provision-operator
    sources:
    - https://github.com/panteparak/db-provision-operator
    type: application
    urls:
    - https://panteparak.github.io/db-provision-operator/charts/db-provision-operator-0.1.7.tgz
    version: 0.1.7
generated: "2026-01-28T08:06:20.132367107Z"
