apiVersion: v1
entries:
  db-provision-operator:
  - apiVersion: v2
    appVersion: 0.1.4
    created: "2026-01-24T02:06:28.772203641Z"
    description: A Kubernetes operator for managing database provisioning (databases,
      users, roles, grants, backups)
    digest: fb29cf7d9f796a85e37d7951d1f1fc1a8e2e1393c8c38c55538588916d3df9c0
    home: https://github.com/panteparak/db-provision-operator
    keywords:
    - database
    - postgresql
    - mysql
    - operator
    - kubernetes
    - provisioning
    - backup
    kubeVersion: '>=1.26.0-0'
    maintainers:
    - name: panteparak
    name: db-provision-operator
    sources:
    - https://github.com/panteparak/db-provision-operator
    type: application
    urls:
    - https://panteparak.github.io/db-provision-operator/charts/db-provision-operator-0.1.4.tgz
    version: 0.1.4
generated: "2026-01-24T02:06:28.770983213Z"
