apiVersion: dbops.dbprovision.io/v1alpha1
kind: DatabaseRestore
metadata:
  labels:
    app.kubernetes.io/name: db-provision-operator
    app.kubernetes.io/managed-by: kustomize
  name: databaserestore-sample
spec:
  # TODO(user): Add fields here
